my_portfolio/basic_functionality/urls.py
from django.urls import path
from .views import MainView, dashboard, RegisterUser, cv_show, RegisterUserDone
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = (
    path('', MainView.as_view(), name='main_view'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('password_change_done')),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('dashboard/', dashboard, name='dashboard'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('register/done/', RegisterUserDone.as_view(), name='register_done'),
    path('Dobromir_Matuszak_CV/', cv_show, name='CV'),
)

my_portfolio/my_blog/urls.py
from django.urls import path
from .views import post_detail, post_list, PostListView, TaggedListView

urlpatterns = (
    path('blog/<slug:slug>/', PostListView.as_view(), name='post_list_by_tag'),
    path('blog/', PostListView.as_view(), name='post_list'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail,
         name='post_detail'),
)

my_portfolio/my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('basic_functionality.urls')),
    path('', include('my_blog.urls')),
    path('', include('my_poll.urls')),
    path('', include('traveler_game.urls')),
    path('admin/', admin.site.urls),
]

my_portfolio/traveler_game/urls.py
from .views import travel_view
from django.urls import path
app_name = "traveler_games"

urlpatterns = (
    path('champ_name/', travel_view, name='creation_hero'),
)

my_portfolio/basic_functionality/models.py
from django.db import models

# Create your models here.

my_portfolio/basic_functionality/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email', 'first_name']

my_portfolio/basic_functionality/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from django.http import FileResponse
import os


# Create your views here.

class MainView(TemplateView):
    template_name = 'index.html'


class RegisterUser(CreateView):
    template_name = 'registration/register.html'
    success_url = reverse_lazy('register_done')
    form_class = UserRegisterForm

    def form_valid(self, form):
        form.save()
        return redirect('register_done')


class RegisterUserDone(TemplateView):
    template_name = 'registration/register_done.html'


@login_required
def dashboard(request):
    return render(request,
                  'registration/dashboard.html',
                  {'section': 'dashboard'})


def cv_show():
    filepath = os.path.join('static',
                            '/home/dob/PycharmProjects/my_portfolio/my_portfolio/'
                            'basic_functionality/static/Dobromir Matuszak - IT CV.pdf')
    return FileResponse(open(filepath, 'rb'), content_type='application/pdf')

my_portfolio/basic_functionality/templates/basic_user_func.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
</head>
<body>

<div class="log">
    {% block content %}
    {% endblock %}
</div>
<div style="clear:both;"></div>
</body>
</html>

my_portfolio/basic_functionality/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8"/>
    <title>Portfolio - Dobromir Matuszak</title>
    <meta name="description" content="Witam, chciałbym się przedstawić,opowiedzieć o sobie oraz pokazać kilka wykonanych przeze mnie projektów"/>
    <meta name="keywords" content="CV, Job, web master, Python, Django, HTML, CSS, Sqlite3"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="author" content="Dobromir Matuszak"/>

    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/fontello/css/fontello.css' %}" type="text/css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://font's.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Lato&display=swap" rel="stylesheet">
</head>
<body>

<div id="container">

    <div class="rectangle">
        <div id="logo">Dobromir Matuszak</div>
        <div class="login_out">
            {% if request.user.is_authenticated %}

                Witaj, <a href="{% url 'dashboard' %}" class="transfer_login_out"> {{ request.user }}</a>!
                <a href="{% url 'logout' %}" class="transfer_login_out">Wyloguj</a>
            {% else %}
                <a href="{% url 'login' %}" class="transfer_login_out">Logowanie</a>
            {% endif %}

        </div>

    </div>

    <div class="square">

        <div class="tile1">
            <a href="http://127.0.0.1:8000/" target="_blank" class="transfer"><i class="icon-user"></i></br>Who am I?</a>


        </div>

        <div class="tile1">
            <a href="{% url 'CV' %}" target="_blank" class="transfer"><i class="icon-graduation-cap"></i>
            </br>
            Curriculum vitaea</a>
        </div>

        <div style="clear:both;"></div>

        <div class="tile2">
            <a href="http://127.0.0.1:8000/poll" target="_blank" class ="transfer"><i class="icon-doc-text"></i>
            </br>

            poll
            </a>
        </div>

        <div class="tile3">
            <a href="http://127.0.0.1:8000/blog" target="_blank" class="transfer"><i class="icon-blogger"></i>log</a>

        </div>
        <div style="clear:both;"></div>

        <div class="tile4">
            <a href="{% url 'traveler_games:creation_hero' %}" target="_blank" class="transfer2"><i class="icon-gamepad"></i></br>Traveler
            </a>
        </div>

    </div>

    <div class="square">

        <div class="tile5"></br>Technologies and sources used for current project
            </br></br>
            <div class="tools1">
                <i class="icon-css"></i>
                  Css3
            </div>
            <div class="tools1">
                <i class="icon-html5"></i>
                Html 5
            </div>

            <div class="tools2">
                <img src="{% static 'css/img/py.png' %}">
                Python
            </div>
            <div class="tools2">
                <img src="{% static 'css/img/dj.png' %}">
                Django
            </div>
            <div class="tools2">
                <img src="{% static 'css/img/sql.png' %}">
                Postgresql
            </div>
        </div>


        <div class="tile6">
            </br></br>
                "Zawsze programuj jak gdyby osoba zajmująca się twoim kodem w przyszłości była agresywnym psychopatą, który wie gdzie mieszkasz." - Martin Golding
        </div>


    </div>
    <div style="clear:both;"></div>

    <div class="rectangle">
        <div class="footer">2022 © Dobromir Matuszak - Portfolio</div>
    </div>

</div>


</body>

</html>